[application]

# App (Project) Name
name = "personal-webpage"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

# `build` & `serve` dist path
out_dir = "docs"
#out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "personal-webpage"

#base_path = "Destroyerrrocket.github.io"
[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

index_on_404 = false

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["./css/tailwind.css", "./css/hamburgers-min.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
