/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const hello_world: () => void;
export const main: (a: number, b: number) => number;
export const __wbg_jsowner_free: (a: number, b: number) => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: number) => number;
export const intounderlyingsource_cancel: (a: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: number) => number;
export const intounderlyingsink_close: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: number) => number;
export const __wbindgen_export_0: (a: number, b: number) => number;
export const __wbindgen_export_1: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_2: (a: number) => void;
export const __wbindgen_export_3: (a: number, b: number, c: number) => void;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export_5: (a: number, b: number) => void;
export const __wbindgen_export_6: (a: number, b: number, c: number) => void;
export const __wbindgen_export_7: (a: number, b: number, c: number, d: number, e: number) => void;
export const __wbindgen_export_8: (a: number, b: number, c: number) => void;
export const __wbindgen_export_9: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_start: () => void;
