[build]
rustflags = [
	#	"-Clto",
	#	"-Zvirtual-function-elimination",
	#"-Zlocation-detail=none",
	#"-Zfmt-debug=none",
]

#[unstable]
#build-std = ["std", "panic_abort", "core", "alloc"]
#build-std-features = ["panic_immediate_abort"]
